title: Wonder's Land
description: Wonder wants to be a TA.
show_downloads: true

baseurl:  # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://wonderly321.github.io" # change this to the base hostname & protocol for your site


google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: jekyll-theme-cayman-blog

# social

github: wonderly321
mail: wonderly321@gmail.com

# Comment
comment:
    disqus: vno-jekyll

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['Home', 'Works', 'Tags', 'About']
